FROM python:3.11-slim

WORKDIR /app

# Installation des dépendances
COPY app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copie du code
COPY . .

# Lance le scraper
CMD ["python", "seed_db.py"]
